FROM amazoncorretto:17.0.7-alpine

RUN mkdir /etc/demo

COPY ./target/demo-0.0.1-SNAPSHOT.jar ./etc/demo

#ENV PROFILE=TODO

EXPOSE 8080

#CMD ["java", "-jar", "-Dspring.profiles.active=${PROFILE}", "/etc/demo/demo-0.0.1-SNAPSHOT.jar"]
CMD ["java", "-jar", "/etc/demo/demo-0.0.1-SNAPSHOT.jar"]
